---
log:
  level: debug

gitlab:
  url: https://gitlab.com
  token: <your_token>

server:
  webhook:
    enabled: true
    secret_token: <strong_arbitrary_secret_token>

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

projects:
  # Configure a project on which you are authorized to configure webhooks
  - name: <your_project_path_with_namespace>
