---
version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    funlen:
      lines: -1 # (disabled)
      statements: 100

    cyclop:
      max-complexity: 20

    lll:
      line-length: 140

    nestif:
      min-complexity: 18

    gosec:
      excludes:
        # https://github.com/golangci/golangci-lint/discussions/4939
        # Disabled by default in golangci because it's too noisy, too many false positives
        - G115
    staticcheck:
      checks:
        - all
        # Seems buggy
        - -ST1000
        # Not personally fond of having to remove those embedded field calls.
        - -QF1008

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mvisonneau)
