builds:
  - main: ./cmd/gitlab-ci-pipelines-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath

snapshot:
  name_template: '{{ .Tag }}-{{ .ShortCommit }}'

changelog:
  skip: true
