before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/gitlab-ci-pipelines-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - description: &description GitLab CI pipelines exporter (prometheus/open-metrics)
    homepage: &homepage https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
    folder: Formula
    tap:
      owner: mvisonneau
      name: homebrew-tap

scoop:
  description: *description
  homepage: *homepage
  license: Apache 2.0
  bucket:
    owner: mvisonneau
    name: scoops

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

snapshot:
  name_template: '{{ .Tag }}-{{ .ShortCommit }}'

changelog:
  skip: true
