before:
  hooks:
    - make man-pages
    - make autocomplete-scripts

builds:
  - main: ./cmd/gitlab-ci-pipelines-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
    flags:
      - -trimpath

universal_binaries:
  - {}

archives:
  - name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - helpers/*

nfpms:
  - maintainer: &author Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: &description GitLab CI pipelines exporter (prometheus/open-metrics)
    license: &license Apache-2.0
    homepage: &homepage https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
    vendor: *author
    file_name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: ./helpers/autocomplete/bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/autocomplete/zsh
        dst:  /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/copyright
        file_info:
          mode: 0644

release:
  disable: true

# Disabling until https://github.com/canonical/snapcraft/issues/4769 is resolved
#snapcrafts:
#  - summary: GitLab CI pipelines exporter (prometheus/open-metrics)
#    description: Monitor GitLab CI pipelines related metrics.
#    license: Apache-2.0
#    confinement: strict
#    grade: devel
#    apps:
#      gitlab-ci-pipelines-exporter:
#        plugs: [home, network, network-bind]

dockers:
  - image_templates:
      - 'docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-amd64'
      - 'ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-amd64'
      - 'quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-amd64'
    ids: [gitlab-ci-pipelines-exporter]
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-arm64'
      - 'ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-arm64'
      - 'quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-arm64'
    ids: [gitlab-ci-pipelines-exporter]
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv6'
      - 'ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv6'
      - 'quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv6'
    ids: [gitlab-ci-pipelines-exporter]
    goarch: arm
    goarm: 6
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv7'
      - 'ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv7'
      - 'quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv7'
    ids: [gitlab-ci-pipelines-exporter]
    goarch: arm
    goarm: 7
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest
    image_templates:
      - docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-amd64
      - docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-arm64
      - docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv6
      - docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv7

  - name_template: ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest
    image_templates:
      - ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-amd64
      - ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-arm64
      - ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv6
      - ghcr.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv7

  - name_template: quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest
    image_templates:
      - quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-amd64
      - quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-arm64
      - quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv6
      - quay.io/mvisonneau/gitlab-ci-pipelines-exporter:latest-armv7

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

checksum:
  name_template: '{{ .ProjectName }}_edge_sha512sums.txt'
  algorithm: sha512

changelog:
  disable: true
