version: 2
before:
  hooks:
    - make autocomplete-scripts

builds:
  - main: ./cmd/gitlab-ci-pipelines-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
    flags:
      - -trimpath
    ignore:
      - { goos: darwin, goarch: arm }

universal_binaries:
  - {}

archives:
  - name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE
      - helpers/*

release:
  disable: true

dockers_v2:
  - images:
      - ghcr.io/einstux/gitlab-ci-pipelines-exporter
    tags:
      - latest
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "{{ .ProjectName }}"
      org.opencontainers.image.url: "https://github.com/einstux/gitlab-ci-pipelines-exporter"
      org.opencontainers.image.source: "https://github.com/einstux/gitlab-ci-pipelines-exporter"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: "Apache-2.0"

checksum:
  name_template: '{{ .ProjectName }}_edge_sha512sums.txt'
  algorithm: sha512

changelog:
  disable: true
