---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/from: deploy.{{ include "app.fullname" . }}
{{ with .Values.service.labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: 80
      targetPort: 8080
      protocol: TCP
  {{- with .Values.service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/from: deploy.{{ include "app.fullname" . }}
