apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ with .Values.labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      helm.sh/from: deploy.{{ include "app.fullname" . }}
{{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/from: deploy.{{ include "app.fullname" . }}
{{ with .Values.podLabels }}{{ toYaml . | indent 8 }}{{ end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{ with .Values.podAnnotations }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/gitlab-ci-pipelines-exporter
{{- with .Values.args }}
          args: {{ toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.envVariables }}
          env: {{ toYaml . | nindent 16 }}
{{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/config.yml
              subPath: config
          ports:
            - name: exporter
              containerPort: 8080
              protocol: TCP
{{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
{{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ template "app.fullname" . }}-config
