{
 "title": "GitLab CI Pipelines Statuses",
 "description": "This dashboard leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses. More information here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "OWNER",
    "label": "owner",
    "query": "label_values(gitlab_ci_pipeline_id, project)"
   },
   {
    "name": "REF",
    "label": "ref",
    "query": "label_values(gitlab_ci_pipeline_id{project=~\"$OWNER.*\"}, ref)"
   }
  ]
 },
 "panels": [
  {
   "title": "FAILED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_status{status=\"failed\", project=~\"$OWNER.*\", ref=~\"$REF\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Average Pipeline Run Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - gitlab_ci_pipeline_timestamp{project=~\"$OWNER.*\", ref=~\"$REF\"})"
    }
   ]
  },
  {
   "title": "Average Pipeline Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_duration_seconds{project=~\"$OWNER.*\", ref=~\"$REF\"})"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(gitlab_ci_pipeline_status{status=\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"} * 1 > 0) or (gitlab_ci_pipeline_status{status=\"running\", project=~\"$OWNER.*\", ref=~\"$REF\"} * 2 > 0) or (gitlab_ci_pipeline_status{status=\"failed\", project=~\"$OWNER.*\", ref=~\"$REF\"} * 3 > 0)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "FAILED",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max(time() - gitlab_ci_pipeline_timestamp{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) unless (max(gitlab_ci_pipeline_status{status!~\"failed\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) > 0)"
    },
    {
     "expr": "(max(gitlab_ci_pipeline_duration_seconds{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) unless (max(gitlab_ci_pipeline_status{status!~\"failed\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref)) > 0)"
    },
    {
     "expr": "min(gitlab_ci_pipeline_status{status=~\"failed\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) > 0"
    }
   ]
  },
  {
   "title": "HEALTHY & RUNNING",
   "type": "table-old",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "max(time() - gitlab_ci_pipeline_timestamp{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) unless max(gitlab_ci_pipeline_status{status!~\"success|running\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_duration_seconds{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) unless (max(gitlab_ci_pipeline_status{status!~\"success|running\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref) > 0)"
    }
   ]
  }
 ]
}